import { StyleSheet } from "react-native";

export const GlobalStyle = StyleSheet.create({
    containerBody: {
        backgroundColor: "#000000",
        height: "100%",
        width: "100%",
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        color: "#ff640a",
        fontFamily: "MsTrebuchet",
        padding: 0,
        margin: 0,
    },
    containerBodyLogin: {
        backgroundColor: "#000000",
        maxHeight: 844,
        maxWidth: 390,
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        color: "#ff640a",
        fontFamily: "MsTrebuchet",
        padding: 0,
        margin: 0,
    },
    header: {
        color: "#ffffff",
        padding: 20,
        width: "100%",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 5,
        display: "flex",
        flexDirection: "row",
        margin: 0,
        position:"absolute",
        top: 0,
        fontFamily:"MsTrebuchet",
        fontSize: 28,
    },
    headerLogin: {
        padding: 20,
        width: "100%",
        height: 50,
        alignItems: "center",
        justifyContent: "center",
        display: "flex",
        flexDirection: "row",
        margin: 0,
        position:"absolute",
        top: 0,
        color: "#ff640a",
        fontSize: 28,
    },
    bodyTexts: {
        color:"#ffffff",
        fontSize: 25,
        position: "absolute",
        top: 75,
        fontWeight: 500,
    },

    containerCardLogin: {
        position: "absolute",
        top: 95,
        alignItems: "center",
        width: 650,
        height: 300,
        marginTop: 20,
        padding: 20,
    },
    containerCardLoginButton:{
        position: "absolute",
        top: 320,
        display: "flex",
        flexDirection: "column",
        gap: 20,
        alignItems: "center",
        justifyContent: "center",
        width: "95%",
    },
    buttonLogin: {
        backgroundColor: "#000000",
        borderColor: "#59595b",
        color: "#59595b",
        borderWidth: 2,
        width: 144,
        height: 34,
        fontSize: 20,
        alignItems: "center",
        justifyContent: "center",
    },
    backButton: {
        backgroundColor: "#000000",
        color: "#ff640a",
        width: 150,
        height: 54,
        fontSize: 22,
        fontWeight: 600,
        alignItems: "center",
        justifyContent: "center",
    },
    containerCardPhoto: {
        width: "100%",
        alignItems: "center",
        position: "absolute",
        top: 72,
        margin: 0,
        height: 500,
    },
    CardImage: {
        width: "100%",
        height: 500,
    },
    ContainerPlay:{
        position: "absolute",
        alignItems: "center",
        justifyContent: "center",
        display: "flex",
        flexDirection: "row",
        gap: 15,
        top: 580,
        width: "100%",
        height: 50,
    },
    watchButton:{
        width: "80%",
        backgroundColor: "#ff640a",
        height: 50,
        alignItems: "center",
        justifyContent: "center",
        fontWeight: 900,


    },
    PlayIcon:{
        position: "absolute",
        left: 30,
        fontSize: 30,
        color: "#000000",
    },
    BookMark:{
        borderColor: "#ff640a",
        backgroundColor: "#000000",
        fontWeight: 900,
        borderWidth: 2,
        fontSize: 25,
        padding: 10,
    },
    ContainerSeries:{
        display: "flex",
        backgroundColor: "#000000",
        flexDirection: "row",
        gap: 80,
        alignItems: "center",
        position: "relative",
        margin: 0,
        width: "100%",
        top: 350,
    },
    CardSeries:{
        width: "auto",
        display: "flex",
        flexDirection:"column",
        fontFamily: "MsTrebuchet",
        backgroundColor: "#000000",
        marginRight: 5,
        marginLeft: 5,
        gap: 3,
    },
});
